"My First R program"

**1. Print**

In [3]:
print (" I love you")

cat ("R", "Program")

print (paste("R","Progran"))

[1] " I love you"
R Program[1] "R Progran"

**2. Variable and Data Type**

In [5]:
myString <- "I Love R Programming"
wholeNum <- 10
floatingNum <- 9.9
isBool <- TRUE

print (myString)

class(myString)
class(wholeNum)
class(floatingNum)
class(isBool)

[1] "I Love R Programming"

[1] "character"

[1] "numeric"

[1] "numeric"

[1] "logical"

**3. Numerical Operators**

In [6]:
x <- 10
y <- 3

add <- x + y
sub <- x - y
mul <- x * y
div <- x / y
mod <- x %% y
exp <- x ^ y

print(add)
print(sub)
print(mul)
print(div)
print(mod)
print(exp)

[1] 13
[1] 7
[1] 30
[1] 3.333333
[1] 1
[1] 1000

**4. User Input**

In [9]:
name <- readline("Enter name: ")

cat("Hello to R Programming: ", name)

Enter name: Sir Rudi Martin Sanchez
Hello to R Programming:  Sir Rudi Martin Sanchez

**5. Decision Making**

In [11]:
grade <- 73

if (grade < 75){
  print ("Failed")
}else{
  print ("Passed")
}

[1] "Failed"

**6. Loop**

In [13]:
for(i in 1:5){
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5

**7. Function**

In [20]:
addNumber <- function(a,b){
  return (a+b)
}

addNumber(3,7)

[1] 10

**8. Vectors**

In [15]:
grades <- c(98,80,91,88,96)

grades

cat("MEAN: ",mean(grades))
cat("\nMax: ",max(grades))
cat("\nMin: ",min(grades))
cat("\nLength: ",length(grades))
cat("\nMedian: ",median(grades))
summary(grades)

[1] 98 80 91 88 96

MEAN:  90.6
Max:  98
Min:  80
Length:  5
Median:  91

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   80.0    88.0    91.0    90.6    96.0    98.0

**9. Matrices**

In [19]:
A <-matrix(c(1,2,3,4,5,6),nrow=2)
A

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

**10. List**

In [21]:
students <- list(
Name = "Ayi Pogi ng CCS",
Course = "BSCS",
Grade = 99
)

students

$Name
[1] "Ayi Pogi ng CCS"

$Course
[1] "BSCS"

$Grade
[1] 99

**11. Frame**

In [22]:
students <- data.frame(
  name = c("Airelle","Zhen","Yhen"),
  course = c("BSCS","BFS","BSOA"),
  grade = c(99,80,75)
)

students

  name    course grade
1 Airelle BSCS   99
2 Zhen    BFS    80
3 Yhen    BSOA   75

**12. Write to CSV**

In [25]:
#save dataframe to csv file
write.csv(students,"students.csv")

**13. Read CSV File**

In [26]:
data <- read.csv("students.csv")

head(data)
summary(data)

  X name    course grade
1 1 Airelle BSCS   99
2 2 Zhen    BFS    80
3 3 Yhen    BSOA   75

       X              name         course      grade
 Min.   :1.0   Length   :3   Length   :3   Min.   :75.00
 1st Qu.:1.5   N.unique :3   N.unique :3   1st Qu.:77.50
 Median :2.0   N.blank  :0   N.blank  :0   Median :80.00
 Mean   :2.0   Min.nchar:4   Min.nchar:3   Mean   :84.67
 3rd Qu.:2.5   Max.nchar:7   Max.nchar:4   3rd Qu.:89.50
 Max.   :3.0                               Max.   :99.00